---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vm_name: "test_ipam"
    vcenter_hostname: "vcenter_hostname"
    vcenter_user: "vcenter_user"
    vcenter_password: "vcenter_password"
    vcenter_dc: "dc1"
    tag_name: "a_tag"
    tag_op: "tag" #[tag | untag]

  - name: Get facts about tag
    vmware_tag_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
    register: tag

  # - name: Print tag
  #   debug: "msg='{{ tag }}'"

  - name: Get tag id
    set_fact:
      tag_id: "{{ item.value.tag_id }}"
    when: item.key == tag_name
    with_dict: "{{ tag.tag_facts }}"
    register: tag_id

  # - name: Print tag
  #   debug: "msg='{{ tag_id }}'"

  - name: Tag vm
    command: ./tag-operation.py {{ tag_op }} {{ tag_id }} {{ vm_name }}
